version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pg-database
    env_file:
      - ./.env.pg.production
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis-db
    restart: always
    ports:
      - 6379:6379

  nestjs-app:
    image: ruarteoctavio8/tateti-backend:0.1.0
    container_name: nestjs-app
    restart: always
    env_file:
      - ./.env.server.production
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis

  react-app:
    image: ruarteoctavio8/tateti-app:0.1.1
    container_name: react-webapp
    restart: always
    ports:
      - 80:80
    depends_on:
      - nestjs-app

volumes:
  postgres_data:
