version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: oruarte
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis-db
    restart: always
    ports:
      - 6379:6379

  nestjs-app:
    build: ./server
    restart: always
    env_file:
      - ./.env.server.production
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis

  react-app:
    build: ./client
    ports:
      - 80:80
    depends_on:
      - nestjs-app

volumes:
  postgres_data:
