version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pg-database
    env_file:
      - ./.env.pg
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - game-net

  redis:
    image: redis:7.2
    container_name: redis-db
    restart: always
    ports:
      - 6379:6379
    networks:
      - game-net

  nestjs-app:
    image: ruarteoctavio8/tateti-backend:0.1.0
    container_name: nestjs-app
    restart: always
    env_file:
      - ./.env.server
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    networks:
      - game-net

  react-app:
    build: ./client
    container_name: react-webapp
    restart: always
    ports:
      - 80:80
    depends_on:
      - nestjs-app
    networks:
      - game-net

networks:
  game-net:
    driver: bridge
volumes:
  postgres_data:
